### PR TITLE
Pandora v2.0.0

### PR DESCRIPTION
**Pull request by kjwinfield**
Version 2.0.0 of pandora has the following new features

-  New pull_from_csv.py script to take required data for submission from an input csv
- New push_to_clinvar.py to script to push variants to ClinVar via API
- New get_clinvar_accession.py script to get an accession ID given a submission ID in ClinVar
- Update bash script to have running modes so it can run the app differently depending on what running mode is set
- Add unit tests for new functionality

Example DNAnexus job using updated app (https://platform.dnanexus.com/panx/projects/Gg2G26Q409xJXX3Ky8xx3Vqy/monitor/job/GgZ8BYQ409x5fXyjJ6b4jY2v)

Variant submission from CUH resulting from this job:
image
Link to the variant record in ClinVar:
https://www.ncbi.nlm.nih.gov/clinvar/variation/49821/
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)

### CODE REVIEW

**Review by pofuoku — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @kjwinfield and @mattgarner)

___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 49 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSLoMN65HOMX1LqkUL:-NxSLoMN65HOMX1LqkUM:b4tonul) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L49)):*
> ```Python
>             "retrieve any files listed"
>         )
>         summary_files = responses[0]["files"]
> ```

Are they cases where the list `responses` have more than one time? if so are you only interested in the summary_files from the first item on the list. `responses[0]` ??
___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 61 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSN-j80hG0-AfUiR2N:-NxSN-j80hG0-AfUiR2O:bubaxj7) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L61)):*
> ```Python
>                 )
>             file_content = json.loads(f_response_content)
>             file["value"] = file_content
> ```

Do you need this? why assigning `file_content` to `file["value"]`.
___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSOYBZCF6g8K3varHu:-NxSOYBZCF6g8K3varHv:bn1t225) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L65)):*
> ```Python
> 
>     return status_response
> ```

You looped through `summary_files`; assigned the response_content to status_response; the value of `status_response` returned here is for the last iteration. Was that intended? Why the loop if you are only interested in one value?

In addition, you first assigned the value of `json,loads(response_content)` to `status_responce` in the first block; checks if `len(responses)==0`, then assigned the response from url in file to `status_response`.  which was later passed to the `get_accession_id()`, which gets the id via keys in the dict. My concern is, will that throw a key error in cases where `len(responses)==0` is true. Because the returned status_response for this case have responses: [] (`actions[0] == "submitted"`) and have a different schema to the other cases. (actions[0]=="error" or "processing" or "processed"??
___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSUQIG4DQ9lrzuczQL:-NxSUQIG4DQ9lrzuczQM:b-lnu5rr) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L82)):*
> ```Python
>             0
>             ]["identifiers"]["clinvarAccession"]
>     else:
> ```

Sequel to above: will you get an Key error in cases the response schema is different above eg for staus: submitted, the following status_response is what we get

___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 138 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSVg3C07Io9LIenmEb:-NxSVg3C07Io9LIenmEc:bat96gu) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L138)):*
> ```Python
>             time.sleep(300)
>             counter += 1
>             run_submission_status_check(
> ```

Does this loop breaks if accession_id was found before the 12 attempts?

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: 7 of 13 files reviewed, 5 unresolved discussions (waiting on @mattgarner and @pofuoku)

___
*[`resources/home/dnanexus/get_clinvar_accession.py` line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-NxSOYBZCF6g8K3varHu:-NxX_px14NQo9fqMkLX8:bn4ske7) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/be74398a45181d126d9586afe5766cf62bcd7aa4/resources/home/dnanexus/get_clinvar_accession.py#L65)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Similar to above there is only one summary file, as there will be only one submission per run of this script.

**Review by pofuoku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: all files reviewed, 4 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 7 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4BRfe7EBKug9bQBHP:-Ny4BRfe7EBKug9bQBHQ:b6e53bf) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L7)):*
> ```JSON
>     "dxapi": "2.0.0",
>     "version": "2.0.0",
>     "properties": {
> ```

Could you add a whatsNew?



_Code quote:_
```JSON
"properties"
```
___
*[`dxapp.json` line 82 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4CvjO2-g0IXn5PLXz:-Ny4CvjO2-g0IXn5PLY-:b3lc7l9) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L82)):*
> ```JSON
>         {
>         "name": "variant_csv",
>         "label": "A csv file with the variant data that is to be submitted to ClinVar",
> ```

What should the content of this file be? Hopefully described in the readme - adding note here as reminder to check



_Code quote:_
```JSON
A csv file with the variant data that is to be submitted to ClinVar
```
___
*[`dxapp.json` line 100 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4DAg-9vKKx1zO-_a0:-Ny4DAg-9vKKx1zO-_a1:b-kd8umi) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L100)):*
> ```JSON
>       },
>       {
>       "name": "submission_id",
> ```

Should this be "clinvar_submission_id" for clarity, since pandora can now submit to multiple variant repositories, not just clinvar?



_Code quote:_
```JSON
submission_id
```
___
*[`dxapp.json` line 107 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4D_Sr3tVBtx24BmCS:-Ny4D_Ss9s6FoatDnco_:bne9rtr) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L107)):*
> ```JSON
>       },
>       {
>       "name": "accession_id",
> ```

As previous comment



_Code quote:_
```JSON
accession_id
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: all files reviewed, 5 unresolved discussions (waiting on @kjwinfield)

___
*[`README.md` line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4EhW_4Y5gLxedA3dx:-Ny4EhWaBCL-xEgz9BNI:b-tt8c4f) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/README.md#L6)):*
> ```Markdown
> eggd_pandora is a variant sharing system, which takes in variant data from a source and inputs that variant data to a variant database. It can work in two ways:
> 1. Take a case in OpenCGA and submit the variants that have been interpreted for the proband to the DECIPHER database
> 2. Take a csv file of interpreted variants (typically this file will have been made by the variant parser script that gets interpreted variants from an Excel workbook) and submit these variants to the ClinVar database
> ```

perhaps a link to the repo to be unambiguous about which script we mean here?



_Code quote:_
```Markdown
variant parser script
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: all files reviewed, 6 unresolved discussions (waiting on @kjwinfield)

___
*[`src/pandora.sh` line 52 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4M0Fw4yPaXwF4D8ZW:-Ny4M0Fw4yPaXwF4D8ZX:b-41d2sv) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/src/pandora.sh#L52)):*
> ```Shell
>         --clinvar_api_key /home/dnanexus/in/clinvar_api_key/*.txt
>     mkdir /home/dnanexus/out/accession_id
>     mv accession_ids.txt /home/dnanexus/out/accession_id
> ```

Could make this DRYer as follows:

```
if  [ "$running_mode" = "decipher" ]
do decipher things
fi

if [ "$running_mode" = "clinvar" ]
do
...
push_to_clinvar.py
...
fi

if [ "$running_mode" =~ ^(clinvar|get_clinvar_accession)$ ]
```do
...
python3 /home/dnanexus/get_clinvar_accession.py \
...
fi
```
This would avoid repeating the get_clinvar_accession call



_Code quote:_
```Shell
    python3 /home/dnanexus/get_clinvar_accession.py \
        --submission_file /home/dnanexus/out/submission_id/submission_ids.txt \
        --clinvar_api_key /home/dnanexus/in/clinvar_api_key/*.txt
    mkdir /home/dnanexus/out/accession_id
    mv accession_ids.txt /home/dnanexus/out/accession_id

    dx-upload-all-outputs
elif [ "$running_mode" = "get_clinvar_accession" ]
then
    python3 /home/dnanexus/get_clinvar_accession.py \
        --submission_file /home/dnanexus/in/submission_ids_file/*.tsv \
        --clinvar_api_key /home/dnanexus/in/clinvar_api_key/*.txt
    mkdir /home/dnanexus/out/accession_id
    mv accession_ids.txt /home/dnanexus/out/accession_id
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: all files reviewed, 11 unresolved discussions (waiting on @kjwinfield)

___
*[`resources/home/dnanexus/pull_from_csv.py` line 98 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4SrtFExT45htLjv7m:-Ny4SrtFExT45htLjv7n:bie4625) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L98)):*
> ```Python
> 
>     if clinical_significance_description in clinical_significance_valid:
>         clinical_significance_description = clinical_significance_description
> ```

Isn't this effectively "Do nothing"? 

Could this "if" be removed (or perhaps better - put the return under it)
___
*[`resources/home/dnanexus/pull_from_csv.py` line 118 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4UKZ4-EggbDRVKaeD:-Ny4UKZ4-EggbDRVKaeE:b-h1bfr7) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L118)):*
> ```Python
> 
> 
> def check_comment(comment):
> ```

Could this function be given a name which more closely describes what it does? It's not really a check (in that it cannot fail), and it modifies the comment in some cases.



_Code quote:_
```Python
check_comment
```
___
*[`resources/home/dnanexus/pull_from_csv.py` line 131 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4UtVpCZo2e5gcfy4k:-Ny4UtVpCZo2e5gcfy4l:b1v2qas) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L131)):*
> ```Python
> 
> 
> def check_assembly(ref_genome):
> ```

Maybe `determine_assembly` is a more accurate description?



_Code quote:_
```Python
check_assembly
```
___
*[`resources/home/dnanexus/pull_from_csv.py` line 162 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4VRXpACH0by2xqa0O:-Ny4VRXpACH0by2xqa0P:bfdcolu) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L162)):*
> ```Python
> 
> 
> def if_nuh(organisation_id, clinvar_dict):
> ```

Perhaps this could also be renamed - I'd intuitively expect if_x to be either true or false (and so return true or false)



_Code quote:_
```Python
if_nuh
```
___
*[`resources/home/dnanexus/pull_from_csv.py` line 206 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4W7hv8yJ3lJy93Vrz:-Ny4W7hv8yJ3lJy93Vs-:b-e64rav) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L206)):*
> ```Python
>         clinvar_dict = extract_clinvar_information(row)
> 
>         file_name = args.variant_csv.split('/')[-1].split('.')[0]
> ```

https://stackoverflow.com/questions/678236/how-do-i-get-the-filename-without-the-extension-from-a-path-in-python



_Code quote:_
```Python
file_name = args.variant_csv.split('/')[-1].split('.')[0]
```

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: 8 of 13 files reviewed, 11 unresolved discussions (waiting on @mattgarner and @pofuoku)

___
*[`dxapp.json` line 7 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4BRfe7EBKug9bQBHP:-Ny5WjAW-mKRwNfqYPkw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L7)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you add a whatsNew?
</blockquote></details>

Done.
___
*[`dxapp.json` line 82 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4CvjO2-g0IXn5PLXz:-Ny5WfU7-R7KT3I8WaQE:b7v6w10) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L82)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What should the content of this file be? Hopefully described in the readme - adding note here as reminder to check
</blockquote></details>

Done. Added this to readme.
___
*[`dxapp.json` line 100 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4DAg-9vKKx1zO-_a0:-Ny5Wn-P9FWl4kNQhLqx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L100)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be "clinvar_submission_id" for clarity, since pandora can now submit to multiple variant repositories, not just clinvar?
</blockquote></details>

Done.
___
*[`dxapp.json` line 107 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4D_Sr3tVBtx24BmCS:-Ny5WneNDacGr-X_27eO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/dxapp.json#L107)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

As previous comment
</blockquote></details>

Done.
___
*[`README.md` line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4EhW_4Y5gLxedA3dx:-Ny5XcSz2oML5DCRHf9E:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/README.md#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

perhaps a link to the repo to be unambiguous about which script we mean here?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/pull_from_csv.py` line 98 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4SrtFExT45htLjv7m:-Ny5ZKic8b9KlMZkW5UM:bk21dun) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L98)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Isn't this effectively "Do nothing"? 

Could this "if" be removed (or perhaps better - put the return under it)
</blockquote></details>

Done.
Realised these were the same as "nan" is also not in the list of acceptable strings
___
*[`resources/home/dnanexus/pull_from_csv.py` line 118 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4UKZ4-EggbDRVKaeD:-Ny5ZboZ45hMRvv_qIXh:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L118)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this function be given a name which more closely describes what it does? It's not really a check (in that it cannot fail), and it modifies the comment in some cases.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/pull_from_csv.py` line 131 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4UtVpCZo2e5gcfy4k:-Ny5ZcsN3NSQr2HsbAkC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L131)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Maybe `determine_assembly` is a more accurate description?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/pull_from_csv.py` line 162 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4VRXpACH0by2xqa0O:-Ny5Zdi_BmRMzJhFl2Ti:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L162)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps this could also be renamed - I'd intuitively expect if_x to be either true or false (and so return true or false)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/pull_from_csv.py` line 206 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4W7hv8yJ3lJy93Vrz:-Ny5ZeOL9tAdsKykFmef:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/resources/home/dnanexus/pull_from_csv.py#L206)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/678236/how-do-i-get-the-filename-without-the-extension-from-a-path-in-python
</blockquote></details>

Done.
___
*[`src/pandora.sh` line 52 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2#-Ny4M0Fw4yPaXwF4D8ZW:-Ny5Zhqf4YX_-RNAoWRQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/6cba37af936ea5a4538ba987f8987f2fd4686654/src/pandora.sh#L52)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could make this DRYer as follows:

```
if  [ "$running_mode" = "decipher" ]
do decipher things
fi

if [ "$running_mode" = "clinvar" ]
do
...
push_to_clinvar.py
...
fi

if [ "$running_mode" =~ ^(clinvar|get_clinvar_accession)$ ]
```do
...
python3 /home/dnanexus/get_clinvar_accession.py \
...
fi
```
This would avoid repeating the get_clinvar_accession call
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Review by mattgarner — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Pull request merged**
